# This is a workflow for ensuring c++ code quality

name: Code Qulaity 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: C/C++ Lint Action
        uses: shenxianpeng/cpp-linter-action@v1.3.0
        
      - name: Include Guards Check
        uses: sbeyer/include-guards-check-action@v1.0.0
        
        
