name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set Up Directories
      run: mkdir bin; mkdir lib
      
    - name: Install dependencies
      run: make
      
    - name: Run tests
      run: make testall

